spring:
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-name: google
            client-id: 976349536322-j3l4gk88n4ubrpcpf58q1qpf9772n12c.apps.googleusercontent.com
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/google-idp
            authorization-grant-type: authorization_code
            scope:
              - email
              - openid
  datasource:
    url: jdbc:mariadb://localhost:3307/simple-auth
    driver-class-name: org.mariadb.jdbc.Driver
    username: user
    password: userPw
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
    poc: debug
    org.springframework.security: TRACE
