### login
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "user",
    "password": "user"
}

> {%
    client.global.set('X-Session-Id', response.headers.valueOf('X-Session-Id'))
%}

### logout
GET http://localhost:8080/logout
X-Session-Id: {{X-Session-Id}}

### hello
GET http://localhost:8080/hello
X-Session-Id: {{X-Session-Id}}
