### login
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}

> {%
    client.global.set('X-Session-Id', response.headers.valueOf('X-Session-Id'))
%}

### logout
GET http://localhost:8080/logout
X-Session-Id: {{X-Session-Id}}

### hello
GET http://localhost:8080/hello
X-Session-Id: {{X-Session-Id}}

### get code
GET http://localhost:8080/oauth2/authorize?response_type=code&client_id=oidc-client&redirect_uri=http://localhost:8080/check&scope=openid+profile
X-Session-Id: {{X-Session-Id}}

### get token
POST http://localhost:8080/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic oidc-client oidc-secret

grant_type=authorization_code&redirect_uri=http://localhost:8080/check&code=
