### login
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "user",
    "password": "user"
}

### logout
GET http://localhost:8080/logout

### hello
GET http://localhost:8080/hello
